version: '3'

services:
  app:
    build: ./src
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    build: ./postgres
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/postgresql/data/
    restart: always
    

  nginx:
    build: ./nginx
    ports:
      - "${HOST_MACHINE_PORT}:80"
    depends_on:
      - app
    restart: always

volumes:
  db_volume:
